[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
lifinity_cpi_swap = "3x7vyDWQLvY2nBuxCWKRDd7tewBrihiwBRSxZJUumdTX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/killer/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
